on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    name: compile-action
    steps:
    - uses: actions/checkout@v1
    - name: SBT action COMPILE 
      id: sbt
      uses: ./
      with:
        commands: compile
        sbt_project_directory: ./test
  test:
    needs: compile
    runs-on: ubuntu-latest
    name: test-action
    steps:
    - uses: actions/checkout@v1
    - name: SBT action TEST
      id: sbt
      uses: ./
      with:
        commands: test
        sbt_project_directory: ./test

