on:
  push:
    branches:
      - master

jobs:
  action_test:
    runs-on: ubuntu-latest
    name: action test
    steps:
    - uses: actions/checkout@v1
    - name: SBT action test
      id: sbt
      uses: ./
      with:
        commands: "build run test"
        sbt_project_directory: ./test
